In [5]:
import pandas as pd
# ram
data = pd.read_csv("out/s2_raw.csv").loc[:, ["model", "cat", "strategy", "max_mem"]]
data = data.query("strategy != 'baseline'")
# aggregate
data.head()

     model                       cat         strategy   max_mem
1  yolo11n             A_unfinetuned   bo_exploration  6904.097
2  yolo11n             A_unfinetuned  bo_exploitation  6904.097
3  yolo11n             A_unfinetuned      grid_search  6904.097
5  yolo11n  B_finetuned_unsupervised   bo_exploration  8293.878
6  yolo11n  B_finetuned_unsupervised  bo_exploitation  8293.878

In [ ]:
data_gr = data.groupby(["model",]).agg(
    mean_mem=("max_mem", "mean"),
    std_mem=("max_mem", "std"),
).reset_index()
data_gr["mean_mem"] = round(data_gr["mean_mem"] / 1024, 2)  # convert to GB
data_gr["std_mem"] = round(data_gr["std_mem"] / 1024, 2)  # convert to GB
data_gr

      model  mean_mem  std_mem
0  rtdetr-l     20.01     0.70
1   yolo11m     19.60     2.41
2   yolo11n      7.45     1.21